application: nuseniorweeknu
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /bootstrap
  static_dir: bootstrap
- url: /images
  static_dir: images

- url: /schedule
  script: schedule.app
- url: /tickets
  script: tickets.app
- url: /about
  script: about.app
- url: /contact
  script: contact.app
- url: /.*
  script: landing.app
  
libraries:
- name: jinja2
  version: latest